name: Compilador SAEL (Desde Repo Privado)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el código Privado de forma segura
        uses: actions/checkout@v4
        with:
          repository: oscgtz2107-ui/dashboard-app
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: 2. Preparar el motor Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. Construir el APK (Usando Gradle del Servidor)
        run: gradle assembleDebug

      - name: 4. Entregar el APK terminado
        uses: actions/upload-artifact@v4
        with:
          name: SAEL-App-Nativa
          path: app/build/outputs/apk/debug/app-debug.apk
